apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app-container
          image: my-vue-app-web  # Replace with your image name
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer


  